version: '3.7'
services:
  goasync:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/go/src/app
    ports:
      - "8040:8080"